### PR TITLE
[OSFUSE-413]open probes port 8081 for springboot-cxf-jaxrs quickstarts

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Comment by ffang** [comment]
[merge][lgtm]

**Comment by ffang** [comment]
@rawlingsj  
Could you please merge this one? Seems I can't trigger the Jenkins CI node to build and merge now, though I can do it about two weeks ago.
Thanks for your help!

**Comment by nicolaferraro** [comment]
ok to test

**Comment by nicolaferraro** [comment]
[merge]

**Pull request merged**
