### PR TITLE
[OSFUSE-444]CXF quick starts should not define the CXF version

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
add to whitelist

**Comment by ffang** [comment]
[merge]

**Comment by ffang** [comment]
Hi @rawlingsj 

Could you please add me into the Admin list? For both spring-boot-cxf-jaxrs and spring-boot-cxf-jaxws projects.

Thanks
Freeman

**Comment by ffang** [comment]
[merge]

**Pull request merged**
